baseURL = "https://solen2554.github.io/fcaj-workshop/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage = "en"

# Theme
theme = "hugo-theme-learn"

# Outputs
[outputs]
home = ["HTML", "RSS", "JSON"]

# Params chung (English mặc định)
[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  avatar = "/fcaj-workshop/images/avatar.jpg"

# Ngôn ngữ English
[Languages.en]
title = "Internship Report"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

# Ngôn ngữ Vietnamese
[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[Languages.vi.params]
  avatar = "/fcaj-workshop/images/avatar.jpg"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

# Markdown config
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true